export enum ActionTypes {
  HANDLE_NEXT_WEEK = 'HANDLE_NEXT_WEEK',
  HANDLE_PREVIOUS_WEEK = 'HANDLE_PREVIOUS_WEEK',
  HANDLE_NEXT_MONTH = 'HANDLE_NEXT_MONTH',
  HANDLE_PREVIOUS_MONTH = 'HANDLE_PREVIOUS_MONTH',
  HANDLE_NEXT_YEAR = 'HANDLE_NEXT_YEAR',
  HANDLE_PREVIOUS_YEAR = 'HANDLE_PREVIOUS_YEAR',
  TRANSACTION_INPUT_CHANGE = 'TRANSACTION_INPUT_CHANGE',
  SET_TRANSACTION = 'SET_TRANSACTION',
  SET_DATE = 'SET_DATE',
  SET_IS_TRANSACTION_OPEN = 'SET_IS_TRANSACTION_OPEN'
}

export default ActionTypes;
