export const languageWords = {
  EMAIL: 'Email',
  USERNAME: 'Username',
  PASSWORD: 'Password',
  CONFIRM_PASSWORD: 'Confirm password',
  SIGN_UP: 'Sign up',
  SIGN_IN: 'Sign in',
  TRANSACTIONS: 'Transactions',
  TRANSACTION: 'Transaction',
  STATS: 'Stats',
  EXPORT: 'Export',
  ACCOUNT: 'Account',
  ACCOUNTS: 'Accounts',
  DAILY: 'Daily',
  WEEKLY: 'Weekly',
  MONTHLY: 'Monthly',
  YEARLY: 'Yearly',
  PERIOD: 'Period',
  SETTINGS: 'Settings',
  PROFILE: 'Profile',
  EXIT: 'Exit',
  PLEASE_SELECT_AN_ACCOUNT: 'Please select an account',
  PLEASE_SELECT_FROM: 'Please select from',
  PLEASE_SELECT_A_CATEGORY: 'Please select a category',
  PLEASE_SELECT_TO: 'Please select to',
  PLEASE_ADD_AN_AMOUNT: 'Please add an amount',
  THE_AMOUNT_IS_TOO_MUCH: `The balance of `,
  FEES_CAN_NOT_BE_GREATER: "Fees can't be greater then amount",
  PLEASE_ENTER_VALID_EMAIL: 'Please enter a valid email.',
  PLEASE_ENTER_VALID_USERNAME: 'Please enter a valid username.',
  NO_MATCHING_PASSWORDS: 'The password does not match. ',
  PLEASE_ENTER_VALID_PASSWORD: 'Please enter 6-20 characters [A-Z, a-z, 0-9 only].',
  NO_DATA_AVAILABLE: 'No data available. '
};

export default languageWords;
