export const HANDLE_NEXT_MONTH = "HANDLE_NEXT_MONTH";
export const HANDLE_PREVIOUS_MONTH = "HANDLE_PREVIOUS_MONTH";
export const HANDLE_NEXT_YEAR = "HANDLE_NEXT_YEAR";
export const HANDLE_PREVIOUS_YEAR = "HANDLE_PREVIOUS_YEAR";
export const HANDLE_INPUT = "HANDLE_INPUT";
export const SET_TRANSACTION = "SET_TRANSACTION";
